angel908fs/tuneshare

- README.md
- backend/config/db.js
- backend/models/user.js
- backend/package-lock.json
- backend/package.json
- backend/routes/default_route.js
- backend/routes/invalid_routes.js
- backend/routes/user_authentication.js
- backend/server.js
- backend/tests/user_authentication.test.js
- backend/utils/user.js
Added user authentication routes along with some unit tests for it and other required stuff
This PR includes changes such as
1. User authentication routes
2. Default and invalid route handling
3. Unit tests for new routes
4. Refactored imports and exports so they can work nicely with jest
5. Updated readme file
> Routing + backend testing setup

- backend/models/user_creation.js
- backend/package-lock.json
- backend/package.json
- backend/tests/user_authentication.test.js
- backend/tests/user_creation.test.js
- frontend/package-lock.json
- frontend/package.json
Add user account creation and unit tests.
> Add account creation and unit tests

- backend/models/comment.js
- backend/models/post.js
> ADDED POST MODEL

- backend/models/comment.js
- backend/models/post.js
> fixing post and comment models

- backend/routes/spotify_routes.js
new search route allows for track search in query using spotify api module and returns a list of 10 tracks after search
> added route to search for track

- frontend/src/pages/auth/Login/LoginPage.jsx
> fix login page

- backend/models/post.js
- backend/models/user.js
- backend/routes/post_creation.js
- backend/tests/post_creation.test.js
- backend/tests/post_creation_util.test.js
- backend/utils/post.js
Unit Test:
```
> backend@1.0.0 test
> jest
PASS  tests/account_creation_util.test.js
PASS  tests/post_creation.test.js
PASS  tests/post_creation_util.test.js
● Console
console.error
Post creation failure:  Error: Internal Error
at Object.<anonymous> (/home/wsl/TuneShare/backend/tests/post_creation_util.test.js:33:59)
at Promise.then.completed (/home/wsl/TuneShare/backend/node_modules/jest-circus/build/utils.js:298:28)
at new Promise (<anonymous>)
at callAsyncCircusFn (/home/wsl/TuneShare/backend/node_modules/jest-circus/build/utils.js:231:10)
at _callCircusTest (/home/wsl/TuneShare/backend/node_modules/jest-circus/build/run.js:316:40)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at _runTest (/home/wsl/TuneShare/backend/node_modules/jest-circus/build/run.js:252:3) …
```
> Add post routes and unit tests

- backend/models/user.js
- backend/routes/profile.js
- backend/server.js
- backend/tests/profile.test.js
Added a new route to retrieve a user's profile
This PR includes changes such as
1. Added a route for retrieving a user's profile (posts included)
2. Added unit tests for the new route
3. Added some new fields to the User model
> added profile route and updated User model

- backend/routes/spotify_routes.js
modified /search route to output preview url and added routes to handle player controls. i.e.: pause, play, next.
> search returns 30 sec preview url, and added routes for player controls.

- backend/routes/spotify_routes.js
- backend/tests/spotify_routes.test.js
modified /search route and testcase along with the /callback testcase to ensure that the test cases work as intended.
> Spotify play

- backend/models/comment.js
- backend/models/post.js
- backend/models/user.js
- backend/routes/post_creation.js
- backend/tests/login.test.js
- backend/utils/post.js
some database models were using objects for the ID fields, but they are supposed to be strings, otherwise you can't read them
> quix emergency fix

- backend/routes/profile.js
- frontend/package-lock.json
- frontend/src/App.jsx
- frontend/src/components/common/Sidebar.jsx
- frontend/src/pages/Profile/ProfilePage.jsx
changed the userdata on profile,js
passed the userId to the profile route
added a profile link to the side bar
user data is being displayed on ProfilePage
> Pineapple profile

- backend/models/post.js
- backend/models/user.js
- backend/routes/feed.js
- backend/routes/follow_route.js
- backend/routes/getMe_route.js
- backend/routes/invalid_routes.js
- backend/routes/profile.js
- backend/routes/spotify_routes.js
- backend/tests/feed.test.js
- backend/tests/follow.test.js
- backend/tests/profile.test.js
- backend/tests/spotify_routes.test.js
- backend/utils/post.js
- frontend/src/App.jsx
- frontend/src/components/common/Rightbar.jsx
- frontend/src/pages/Profile/ProfilePage.jsx
- frontend/src/pages/auth/Login/LoginPage.jsx
- frontend/src/pages/auth/signup/SignUpPage.jsx
- frontend/src/pages/home/CreatePost.jsx
- frontend/src/pages/home/HomePage.jsx
changed a bunch of comments across multiple files
> quick fixes

- backend/routes/user_search.js
- backend/server.js
- backend/tests/user_search.test.js
- frontend/src/components/common/Rightbar.jsx
- frontend/src/pages/Profile/ProfilePage.jsx
Added a search bar to search for users so people can go to their profiles and follow them
- Added backend route
- Added unit tests for route
- Added frontend components
- Added some reach toast success/error popup messages to both the right sidebar and the profile page (when trying to follow a user)
Manual testing on the frontend
Can follow someone directly from the search bar
Overall look
> User search backend + frontend

- frontend/src/components/common/Post.jsx
we can now see spotify stuff on the posts
> Spotify stuff

- README.md
- frontend/package-lock.json
> my first commit Suada

- backend/models/user.js
- backend/routes/likes.js
- backend/tests/likes.test.js
- frontend/src/components/common/Post.jsx
- frontend/src/components/common/Posts.jsx
Fixed a bug where a user could like the same post several times 🤓
This PR includes changes such as
1. Updated user model to add a liked_posts array so we can perform some checks and prevent users from liking the same post more than once
2. Updated `like` and `unlike` routes
3. Added new route `user-liked-posts`
4. Added a bunch of new unit tests for the likes' backend 
5. Updated `Post.jsx` to perform the checks mentioned in point 1
6. Updated `Posts.jsx` to pass the array of posts liked by the user to each post component, in order to be able to perform checks for points 5 and 1
> Likes bug fix

- frontend/src/pages/home/CreatePost.jsx
*Added Collapsible search bar with music icon as the button
------------------------
Can now add the link or search up a song
_cannot search for playlists or individual artists yet_
> Spotifysearch

- frontend/src/pages/home/CreatePost.jsx
Added useRef from react to have detectable mouse clicks
Cleaned up how the search bar looks
Click in text bar to type in the search
Click outside the search bar to make the search list disappear using useRef
After clicking a song, it will show the song + artists instead of the song link from previous pulls
> Improved search bar

- frontend/src/pages/home/CreatePost.jsx
improved the visuals of the search bar
also, we can now post without any text, just the song
> Frontend work

- frontend/src/components/common/Post.jsx
> visual changes: transparent, larger play button + centered text 

- backend/models/comment.js
- backend/models/user.js
- backend/routes/comments.js
- backend/server.js
- frontend/src/components/common/Post.jsx
we can now post and delete comments on posts
added routes for comments 
updated db models
updated post component
> Comments frontend

- backend/models/user.js
- backend/routes/feed.js
- backend/routes/profile.js
- backend/tests/profile.test.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/Post.jsx
- frontend/src/pages/Profile/EditProfileModal.jsx
- frontend/src/pages/Profile/ProfilePage.jsx
Had alot of changes made to ProfilePage.js, Post.jsx, feed.js, EditProfileModal.jsx, profile.js, user.js
made a new route to profile.js to edit the following:
fullname, username, password ( not sure if it works yet), bio, link
changed the UI in the profile page
Will add the spotify link working later
will add a test for profile.js soon!
currently working on profile image as might as well include since i changed alot for editprofile
> Profilepage

- backend/routes/suggestedUsers.js
- backend/server.js
- frontend/src/components/common/Rightbar.jsx
added suggestedUsers file, added two lines to server.js, and made some changes to rightbar file
> added suggested users functionality

- backend/routes/profile.js
- backend/tests/profile.test.js
Added unit test for route : /profile/update
Fixed all issues in the unit test for profile and update
> fixed and updated profile unit tests

- frontend/src/App.jsx
- frontend/src/pages/admin/adminPage.jsx
> admin page setup

- backend/middleware/logger.js
- backend/models/middleware.js
- backend/server.js
setup for database model and route
> added database model and route

- backend/routes/feed.js
- backend/routes/follow_route.js
- backend/routes/profile.js
- backend/routes/suggestedUsers.js
- backend/routes/user_search.js
- backend/tests/feed.test.js
- backend/tests/follow.test.js
- backend/tests/profile.test.js
- backend/tests/user_search.test.js
- frontend/src/components/common/Post.jsx
- frontend/src/components/common/Rightbar.jsx
- frontend/src/components/common/Sidebar.jsx
- frontend/src/pages/Profile/ProfilePage.jsx
- frontend/src/pages/home/CreatePost.jsx
- Unfollow and Follow work in real time from profile page and the Rightsidebar/searchbar
- accurately shows number go up or down for follower counts and following counts
- Added the isFollowing flag in lots of routes,
- isFollowing flag is to show if you're following the specific user and if you are, it will show the Unfollow button instead
-if the flag is not raised, it will show you the follow button
- pfp shows in the Left/Right Side Bar and on the Create Post
- Added fullNames
- these are different from usernames and are basically another way to identify yourselfs
- can be updated on profile page
- show up on the Posts and on the Left Side Bar near the log out button
- When updated, the left side bar doesn't update until refreshed, meanwhile the feed is updated earlier( probably cause …
> Unfollow & Profile Pictures update

- backend/routes/middleware.js
> fixed logs

- frontend/src/components/common/Post.jsx
Changed a single line in post.jsx thats responsible for recognizing user's verified flag
> should show verified check now

- backend/routes/admin_routes.js
- backend/server.js
> Admin routes

- backend/routes/admin_routes.js
- frontend/src/App.jsx
- frontend/src/pages/admin/UsersDashboard.jsx
- frontend/src/pages/admin/adminPage.jsx
> More dashboards

- backend/routes/admin_routes.js
- frontend/src/App.jsx
- frontend/src/pages/admin/SongsDashboard.jsx
- frontend/src/pages/admin/adminPage.jsx
> added Songs Dashboard

- backend/models/middleware.js
- backend/models/songs.js
- backend/models/user.js
- frontend/src/components/common/Post.jsx
- frontend/src/pages/Profile/ProfilePage.jsx
Fixed bug related to songs and logs TTL: now our DB should accurately delete entries once the TTL expires
Got rid of repeated, unnecessary song metadata fetches due to react's component update rules
> I hope this is my last PR
